package eu.wohlben.qits.telemetry.api;

import static io.restassured.RestAssured.given;

import io.quarkus.test.junit.QuarkusTest;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import org.junit.jupiter.api.Test;

/**
 * Writes {@code docs/openapi.yml} as a side effect of the suite, the same way the monorepo's own
 * {@code OpenApiSchemaExportTest} does. Checking the document in is what turns an API change into a
 * reviewable diff instead of something a caller discovers at runtime.
 *
 * <p>This is a test only because {@code @QuarkusTest} is the cheapest way to stand the application
 * up and read its own {@code /observability/q/openapi}. It asserts nothing — the assertion is the
 * diff.
 *
 * <p>What lands in the file is deliberately narrower than what this service serves: {@code
 * /observability/api/otel/v1/*} is {@code @Operation(hidden = true)}, because it is an OTLP wire
 * protocol spoken by SDKs rather than a JSON API. Expect only the five telemetry query operations.
 */
@QuarkusTest
public class OpenApiSchemaExportTest {

  @Test
  public void exportOpenApiSchema() throws Exception {
    String schema =
        given().when().get("/observability/q/openapi").then().statusCode(200).extract().asString();

    // The module is `service/`, so this resolves to the repo root's docs/ — matching the monorepo,
    // where the same test runs from a `service` module too.
    Path docsDir = Paths.get("../docs");
    if (!Files.exists(docsDir)) {
      Files.createDirectories(docsDir);
    }

    String header =
        "# THIS FILE IS GENERATED BY OpenApiSchemaExportTest — DO NOT EDIT MANUALLY.\n"
            + "# Run `./mvnw -pl service test -Dtest=OpenApiSchemaExportTest` to regenerate.\n";

    Files.writeString(docsDir.resolve("openapi.yml"), header + schema);
  }
}
